version: '3.8'

services:
  # Django web service
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    networks:
      - service_network
    depends_on:
      - mongodb
    command: poetry run python manage.py runserver 0.0.0.0:8000

  # MongoDB service
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - mongodb_data:/data/configdb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: database
    networks:
      - service_network

# Mount the volumes
volumes:
    mongodb_data:
        driver: local

# Create a network
networks:
    service_network:
        driver: bridge